services:
    # PostgreSQL
    db:
        image: postgres:15-alpine
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secretpassword
            POSTGRES_DB: transaction_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - enterprise-net

    # pgAdmin
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_gui
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: gyuri@dev.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - db
        networks:
            - enterprise-net

    # Python Backend (FastAPI)
    backend:
        build: ./backend-python
        container_name: python_backend
        restart: always
        environment:
            DATABASE_URL: postgresql://enterprise_user:secretpassword123@terraform-20260319170056534900000001.cj6q4osu8let.eu-central-1.rds.amazonaws.com:5432/transaction_db
        ports:
            - "8000:8000"
        networks:
            - enterprise-net

    # Go Frontend
    frontend:
      build: ./frontend-go
      container_name: go_frontend
      environment:
        - BACKEND_URL=http://python_backend:8000
      ports:
        - "8081:8080"
      networks:
        - enterprise-net
      depends_on:
        - backend

    # Prometheus
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
        networks:
            - enterprise-net

    # Grafana
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        networks:
            - enterprise-net

networks:
    enterprise-net:
        driver: bridge

volumes:
    postgres_data:
